HEALTH_BINARY=healthBrokerService 
#BROKER_BINARY=brokerService


## up: starts all containers in the background without forcing build
up:
	@echo "Starting Docker images..."
	docker-compose up -d
	@echo "Docker images started!"

## up_build: stops docker-compose (if running), builds all projects and starts docker compose
up_build: build_health
	@echo "Stopping docker images (if running...)"
	docker-compose down
	@echo "Building (when required) and starting docker images..."
	docker-compose up --build -d
	@echo "Docker images built and started!"

## down: stop docker compose
down:
	@echo "Stopping docker compose..."
	docker-compose down
	@echo "Done!"

## build_broker: builds the broker binary as a linux executable
#build_broker:
#	@echo "Building broker binary..."
#	cd ../broker_service && env GOOS=linux CGO_ENABLED=0 go build -o ${BROKER_BINARY} .
#	@echo "Done!"

## build_health: builds the health binary as a linux executable
build_health:
	@echo "Building health binary..."
	cd ../health_broker_service && env GOOS=linux CGO_ENABLED=0 go build -o ${HEALTH_BINARY} ./cmd
	@echo "Done!"


